apiVersion: v2
appVersion: "1.0"
dependencies:
- name: common
  repository: https://charts.bitnami.com/bitnami
  tags:
  - bitnami-common
  version: 1.x.x
description: A Helm chart for Kubernetes
name: gohttpserver
version: 2.0.0
home: https://github.com/codeskyblue/gohttpserver
icon:
keywords:
- gohttpserver
maintainers:
- email: 29ygq@sina.com
  name: Chinge Yang
