apiVersion: v2
appVersion: 2.2.0
dependencies:
- name: common
  repository: https://charts.bitnami.com/bitnami
  tags:
  - bitnami-common
  version: 1.x.x
description: Nosqlclient (Formerly Mongoclient), MongoDB Management Tool
engine: gotpl
name: mongoclient
version: 2.0.0
home: https://www.nosqlclient.com
icon: https://raw.githubusercontent.com/nosqlclient/nosqlclient/master/public/logo/full_1.png
keywords:
- mongodb
- client
maintainers:
- email: 29ygq@sina.com
  name: Chinge Yang
sources:
- https://github.com/nosqlclient/nosqlclient/
