apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ template "lam.fullname" . }}
  labels:
    app: {{ template "lam.name" . }}
    chart: {{ template "lam.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
    {{- if .Values.labels }}
{{ toYaml .Values.labels | indent 4 }}
    {{- end }}
data:
  init.sh: |-
    #!/bin/bash
    
    # lam config dir
    lam_config_dir=/var/lib/ldap-account-manager/config
    empty_dir=/tmp/config
    owner=www-data
    
    [ ! -d $empty_dir ] && mkdir $empty_dir
  
    if [ -L $empty_dir/config.cfg ]; then
      rm -f $empty_dir/config.cfg 
      \cp -p $lam_config_dir/config.cfg.sample $empty_dir/config.cfg
    fi
    awk 'BEGIN { cmd="cp -rpi ${lam_config_dir}/* ${empty_dir}/"; print "n" |cmd; }'
    
    chown -R $owner $empty_dir/
{{- if .Values.config.enabled -}}
{{ toYaml .Values.config.data | indent 2 }}
{{- end -}}
