apiVersion: v2
appVersion: "1.3"
dependencies:
- name: common
  repository: https://charts.bitnami.com/bitnami
  tags:
  - bitnami-common
  version: 1.x.x
description: Web interface to change and reset password in an LDAP directory.
engine: gotpl
name: self-service-password
version: 2.0.0
home: https://ltb-project.org/documentation/self-service-password
icon: https://www.ltb-project.org/images/ltb-logo.png
keywords:
- ldap
- password
maintainers:
- email: 29ygq@sina.com
  name: Chinge Yang
sources:
- https://github.com/ltb-project/self-service-password
- https://github.com/tiredofit/docker-self-service-password
