apiVersion: v2
appVersion: 2.3.2
dependencies:
- name: common
  repository: https://charts.bitnami.com/bitnami
  tags:
  - bitnami-common
  version: 1.x.x
description: Chart for the tengine server.
engine: gotpl
name: tengine-sftp
version: 2.0.0
home: http://tengine.taobao.org
icon: http://tengine.taobao.org/img/logo.png
keywords:
- nginx
- tengine
- http
- web
- www
- sftp
- reverse proxy
maintainers:
- email: 29ygq@sina.com
  name: Chinge Yang
sources:
- https://github.com/alibaba/tengine
- https://github.com/ygqygq2/tengine-docker
