{{- if .Values.config }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ template "elasticsearch5.fullname" . }}
  labels:
    app: {{ template "elasticsearch5.name" . }}
    chart: {{ template "elasticsearch5.chart" . }}
    heritage: {{ .Release.Service | quote }}
    release: {{ .Release.Name | quote }}
data:
  elasticsearch.yml: |-
{{ toYaml .Values.config | indent 4 }}
{{- end }}
