apiVersion: v1
kind: Service
metadata:
  annotations:
    service.alpha.kubernetes.io/tolerate-unready-endpoints: "true"
  name: {{ template "elasticsearch5.discovery.fullname" . }}
  labels:
    app: {{ template "elasticsearch5.name" . }}
    chart: {{ template "elasticsearch5.chart" . |}}
    heritage: {{ .Release.Service | quote }}
    release: {{ .Release.Name | quote }}
spec:
  clusterIP: None
  ports:
  - port: 9300
    name: transport
    targetPort: transport
  publishNotReadyAddresses: true
  sessionAffinity: None
  type: ClusterIP
  selector:
    app: {{ template "elasticsearch5.name" . }}
    release: {{ .Release.Name | quote }}
