{{- if .Values.metrics.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ template "elasticsearch5.metrics.fullname" . }}
  labels:
    app: {{ template "elasticsearch5.name" . }}
    chart: {{ template "elasticsearch5.chart" . }}
    heritage: {{ .Release.Service | quote }}
    release: {{ .Release.Name | quote }}
    role: "metrics"
  annotations:
{{ toYaml .Values.metrics.annotations | indent 4 }}
spec:
  type: {{ .Values.metrics.service.type | quote }}
  ports:
  - name: metrics
    port: 9108
    targetPort: metrics
  selector:
    app: {{ template "elasticsearch5.name" . }}
    release: {{ .Release.Name | quote }}
    role: "metrics"
{{- end }}
