{{- if .Values.metrics.enabled }}
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: {{ template "elasticsearch5.metrics.fullname" . }}
  labels:
    app: {{ template "elasticsearch5.name" . }}
    chart: {{ template "elasticsearch5.chart" . }}
    heritage: {{ .Release.Service | quote }}
    release: {{ .Release.Name | quote }}
    role: "metrics"
spec:
  selector:
    matchLabels:
      app: {{ template "elasticsearch5.name" . }}
      release: "{{ .Release.Name }}"
      role: "metrics"
  replicas: 1
  template:
    metadata:
      labels:
        app: {{ template "elasticsearch5.name" . }}
        release: {{ .Release.Name | quote }}
        chart: {{ template "elasticsearch5.chart" . }}
        role: "metrics"
{{- with .Values.metrics.podAnnotations }}
      annotations:
{{ toYaml . | indent 8 }}
{{- end }}
    spec:
{{- include "elasticsearch5.imagePullSecrets" . | indent 6 }}
      containers:
      - name: {{ template "elasticsearch5.metrics.fullname" . }}
        image:  {{ template "elasticsearch5.metrics.image" . }}
        imagePullPolicy: {{ .Values.metrics.image.pullPolicy | quote }}
        args: [ "-es.uri=http://{{ template "elasticsearch5.coordinating.fullname" . }}:{{ .Values.coordinating.service.port }}", "-es.all=true" ]
        ports:
        - name: metrics
          containerPort: 9108
        livenessProbe:
          httpGet:
            path: /metrics
            port: metrics
          initialDelaySeconds: 60
          timeoutSeconds: 5
        readinessProbe:
          httpGet:
            path: /metrics
            port: metrics
          initialDelaySeconds: 5
          timeoutSeconds: 1
        resources:
{{ toYaml .Values.metrics.resources | indent 10 }}
{{- end }}
