apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ template "sftp.fullname" . }}
  labels:
    app: {{ template "sftp.name" . }}
    chart: {{ template "sftp.chart" . }}
    release: "{{ .Release.Name }}"
    heritage: "{{ .Release.Service }}"
data:
{{ toYaml .Values.usersConfFile | indent 2 }}
{{ toYaml .Values.scriptFile | indent 2 }}
{{ toYaml .Values.sshConfFile | indent 2 }}
